# Generated by Django 5.0 on 2026-02-16 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgramPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='academic.academicprogram', verbose_name='Programa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Programa',
                'verbose_name_plural': 'Permisos de Programas',
                'db_table': 'user_program_permissions',
                'indexes': [models.Index(fields=['user'], name='user_progra_user_id_837b08_idx'), models.Index(fields=['program'], name='user_progra_program_fe2dc7_idx')],
                'unique_together': {('user', 'program')},
            },
        ),
    ]
