# Generated by Django 5.0 on 2026-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: 2026-A, 2026-B', max_length=50, unique=True, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('enrollment_start', models.DateField(verbose_name='Inicio de Inscripciones')),
                ('enrollment_end', models.DateField(verbose_name='Fin de Inscripciones')),
                ('is_active', models.BooleanField(default=False, help_text='Solo un periodo puede estar activo a la vez', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'db_table': 'academic_periods',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active'], name='academic_pe_is_acti_2ba4b2_idx'), models.Index(fields=['name'], name='academic_pe_name_ff8ce2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Programa')),
                ('code', models.CharField(help_text='Ej: ISC, LA, TICS', max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duration', models.IntegerField(help_text='Duración en cuatrimestres/semestres', verbose_name='Duración')),
                ('max_capacity', models.IntegerField(default=30, help_text='Capacidad máxima por generación', verbose_name='Capacidad Máxima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
                'db_table': 'academic_programs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='academic_pr_code_e0d05d_idx'), models.Index(fields=['is_active'], name='academic_pr_is_acti_b1b220_idx')],
            },
        ),
    ]
