# Generated by Django 5.0 on 2026-03-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.RenameIndex(
            model_name='enrollmentdocument',
            new_name='enrollment__enrollm_c3ec92_idx',
            old_name='enroll_doc_enrollment_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollmentdocument',
            new_name='enrollment__documen_3d2f7d_idx',
            old_name='enroll_doc_type_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollmentdocument',
            new_name='enrollment__status_a15dfa_idx',
            old_name='enroll_doc_status_idx',
        ),
        migrations.AlterField(
            model_name='enrollmentdocument',
            name='document_type',
            field=models.CharField(choices=[('numero_seguridad_social', 'Número de Seguridad Social'), ('certificado_bachillerato', 'Certificado de Bachillerato'), ('acta_nacimiento', 'Acta de Nacimiento'), ('curp', 'CURP'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('certificado_estudios', 'Certificado de Estudios'), ('fotografia', 'Fotografía'), ('comprobante_pago', 'Comprobante de Pago')], max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='enrollmentdocument',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True, verbose_name='Tamaño'),
        ),
    ]
