# Generated by Django 5.0 on 2026-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentdocument',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del Archivo'),
        ),
        migrations.AlterField(
            model_name='enrollmentdocument',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='enrollment/documents/%Y/%m/', verbose_name='Archivo'),
        ),
    ]
