# Generated by Django 5.0 on 2026-02-04 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('under_review', 'En Revisión'), ('documents_rejected', 'Documentos Rechazados'), ('documents_approved', 'Documentos Aprobados'), ('payment_pending', 'Pago Pendiente'), ('payment_submitted', 'Pago Enviado'), ('payment_validated', 'Pago Validado'), ('exam_scheduled', 'Examen Programado'), ('exam_completed', 'Examen Realizado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='draft', max_length=50, verbose_name='Estado')),
                ('exam_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Examen')),
                ('exam_mode', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('en_linea', 'En Línea')], max_length=20, null=True, verbose_name='Modalidad del Examen')),
                ('exam_location', models.CharField(blank=True, help_text='Aula física o URL de reunión', max_length=255, null=True, verbose_name='Ubicación del Examen')),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación del Examen')),
                ('exam_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Realización del Examen')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación/Rechazo')),
                ('notes', models.TextField(blank=True, help_text='Notas internas de Servicios Escolares', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pre_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado/Rechazado por')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_enrollments', to='academic.academicperiod', verbose_name='Periodo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_enrollments', to='academic.academicprogram', verbose_name='Programa')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pre_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_enrollments', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pre-inscripción',
                'verbose_name_plural': 'Pre-inscripciones',
                'db_table': 'pre_enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('acta_nacimiento', 'Acta de Nacimiento'), ('curp', 'CURP'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('certificado_estudios', 'Certificado de Estudios'), ('fotografia', 'Fotografía')], max_length=50, verbose_name='Tipo de Documento')),
                ('file_path', models.FileField(upload_to='pre_enrollment/documents/%Y/%m/', verbose_name='Archivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True, verbose_name='Tamaño')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=50, verbose_name='Estado')),
                ('reviewer_notes', models.TextField(blank=True, null=True, verbose_name='Notas del Revisor')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('pre_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pre_enrollment.preenrollment', verbose_name='Pre-inscripción')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('announcement_file', models.FileField(blank=True, help_text='PDF de la convocatoria', null=True, upload_to='announcements/', verbose_name='Archivo de Convocatoria')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('deadline', models.DateField(help_text='Fecha límite de registro', verbose_name='Fecha Límite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic.academicperiod', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'db_table': 'announcements',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['period'], name='announcemen_period__44621c_idx'), models.Index(fields=['is_active'], name='announcemen_is_acti_8058e7_idx'), models.Index(fields=['published_at'], name='announcemen_publish_6b0e06_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='preenrollment',
            index=models.Index(fields=['student'], name='pre_enrollm_student_b40673_idx'),
        ),
        migrations.AddIndex(
            model_name='preenrollment',
            index=models.Index(fields=['program'], name='pre_enrollm_program_ee061e_idx'),
        ),
        migrations.AddIndex(
            model_name='preenrollment',
            index=models.Index(fields=['period'], name='pre_enrollm_period__4324ad_idx'),
        ),
        migrations.AddIndex(
            model_name='preenrollment',
            index=models.Index(fields=['status'], name='pre_enrollm_status_590748_idx'),
        ),
        migrations.AddIndex(
            model_name='preenrollment',
            index=models.Index(fields=['submitted_at'], name='pre_enrollm_submitt_f3e6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='preenrollment',
            index=models.Index(fields=['exam_date'], name='pre_enrollm_exam_da_c8fed1_idx'),
        ),
        migrations.AddConstraint(
            model_name='preenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='unique_student_period'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['pre_enrollment'], name='documents_pre_enr_06465a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_status_f31a08_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reviewed_by'], name='documents_reviewe_88c9e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('pre_enrollment', 'document_type'), name='unique_document_per_enrollment'),
        ),
    ]
