# Generated by Django 5.0 on 2026-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='exam_type',
            field=models.CharField(choices=[('propio', 'Propio'), ('cenaval', 'CENAVAL')], default='propio', max_length=20, verbose_name='Tipo de Examen'),
        ),
    ]
