# Generated by Django 5.0 on 2026-03-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'managed': False, 'verbose_name': 'Credencial', 'verbose_name_plural': 'Credenciales'},
        ),
        migrations.RenameIndex(
            model_name='credentialconvocatoria',
            new_name='credential__status_b4187f_idx',
            old_name='cred_conv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='credentialconvocatoria',
            new_name='credential__period__b7b625_idx',
            old_name='cred_conv_period_idx',
        ),
        migrations.RenameIndex(
            model_name='credentialrequest',
            new_name='credential__status_a7c901_idx',
            old_name='cred_req_status_idx',
        ),
        migrations.RenameIndex(
            model_name='credentialrequest',
            new_name='credential__convoca_8d025f_idx',
            old_name='cred_req_conv_idx',
        ),
        migrations.RenameIndex(
            model_name='credentialrequest',
            new_name='credential__enrollm_635a53_idx',
            old_name='cred_req_enrollment_idx',
        ),
    ]
