# Generated by Django 5.0 on 2026-02-03 19:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CURP inválido. Formato: 4 letras, 6 dígitos, H/M, 5 letras, 1 alfanumérico, 1 dígito', regex='^[A-Z]{4}\\d{6}[HM][A-Z]{5}[A-Z0-9]\\d$')], verbose_name='CURP')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, verbose_name='Género')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Email personal (puede diferir del email de usuario)', max_length=255, null=True, verbose_name='Email Personal')),
                ('institutional_email', models.EmailField(blank=True, help_text='Asignado en inscripción', max_length=255, null=True, unique=True, verbose_name='Email Institucional')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('previous_school_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Escuela de Procedencia')),
                ('previous_school_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de la Escuela')),
                ('previous_school_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de la Escuela')),
                ('education_level', models.CharField(blank=True, choices=[('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('bachillerato', 'Bachillerato'), ('tecnico', 'Técnico'), ('universidad', 'Universidad'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Nivel Educativo')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Año de Graduación')),
                ('photo', models.ImageField(blank=True, help_text='Fotografía para credencial', null=True, upload_to='students/photos/%Y/%m/', verbose_name='Fotografía')),
                ('photo_status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=50, verbose_name='Estado de la Fotografía')),
                ('photo_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('photo_rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('photo_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_photos', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'students',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='students_user_id_b061ff_idx'), models.Index(fields=['curp'], name='students_curp_91d133_idx'), models.Index(fields=['first_name', 'last_name'], name='students_first_n_ce3d36_idx'), models.Index(fields=['institutional_email'], name='students_institu_922847_idx'), models.Index(fields=['photo_status'], name='students_photo_s_2cfee6_idx')],
            },
        ),
    ]
