# Generated by Django 5.0 on 2026-02-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
    ]
