# Generated by Django 5.0 on 2026-03-05 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('examen_admision', 'Examen de Admisión'), ('inscripcion', 'Inscripción'), ('colegiatura', 'Colegiatura')], db_column='concept', max_length=100, verbose_name='Tipo de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referencia')),
                ('receipt_file', models.FileField(blank=True, db_column='payment_proof', null=True, upload_to='payment_proofs/%Y/%m/', verbose_name='Comprobante')),
                ('payment_date', models.DateTimeField(blank=True, db_column='paid_at', null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('validated', 'Validado'), ('rejected', 'Rechazado')], default='pending', max_length=50, verbose_name='Estado')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('validation_notes', models.TextField(blank=True, db_column='rejection_reason', verbose_name='Notas de Validación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
